### ISSUE TITLE
Using MATCH_BY_COLUMN_NAME for simpler loading

### ISSUE THREAD

**Issue by dhuang** [snowplow-archive/snowplow-snowflake-loader#100]
In [Snowflake's 3.51 release](https://community.snowflake.com/s/article/3-51-Release-Notes-November-11-2019), they introduced a new [copy option](https://docs.snowflake.net/manuals/sql-reference/sql/copy-into-table.html#copy-options-copyoptions) called `MATCH_BY_COLUMN_NAME` that supports loading semi-structured data in JSON directly into separate columns (rather than a single VARIANT). I believe this enables us to reduce steps 3-5 in [loading steps](https://github.com/snowplow-incubator/snowplow-snowflake-loader/wiki#loading-steps) into a single copy query.

Once concern may be how it handles columns in the S3 files, but not in the Snowflake schema.

> If additional non-matching columns are present in the data files, the values in these columns are not loaded.

Currently if this was the case, the query would error as likely desired. However with `MATCH_BY_COLUMN_NAME`, it would succeed and those extra values would be ignored, eventually becoming null when the columns are added in Snowflake.

Performance benefits are probably minimal, but perhaps fewer queries that can go wrong is a good thing?

**Comment by chuwy** [comment]
This is an amazing idea. we didn't know about this feature. Scheduling for next release.

**Comment by chuwy** [comment]
Hey @dhuang! We've switched to `MATCH_BY_COLUMN_NAME` in new Snowflake Loader (which is part of RDB Loader 3.0.0 framework - will be announced next week).

Although I'm not sure how long we'll have it as it prevents [another feature](https://github.com/snowplow/snowplow-rdb-loader/issues/815) from being implemented.

Anyways, thanks for the advice!
