### ISSUE TITLE
Broken link in the wiki for atomic-def.sql

### ISSUE THREAD

**Issue by davehowell** [snowplow-archive/snowplow-snowflake-loader#103]
In the setup guide: https://github.com/snowplow-incubator/snowplow-snowflake-loader/wiki/Setup-Guide#snowflake

This line links to `atomic-def.sql` and currently goes to a 404: 

> Initial atomic.events DDL for Snowflake can be found in atomic-def.sql.

The correct link is now:
https://github.com/snowplow-incubator/snowplow-snowflake-loader/blob/master/loader/src/main/resources/sql/atomic-def.sql

I would have sent a PR for this, but I learned that [PRs for github wikis are convoluted](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github), so easier to let you know with this issue.

**Comment by chuwy** [comment]
Thanks. Will get it fixed next week when docs migrated to docs.snowplowanalytics.com/

**Comment by chuwy** [comment]
Thanks @davehowell! We've migrated off the wiki and fixed the link https://docs.snowplowanalytics.com/docs/open-source-components-and-applications/snowplow-snowflake-loader/setup/
