### ISSUE TITLE
Add preliminary checks for Snowflake entities

### ISSUE THREAD

**Issue by chuwy** [snowplow-archive/snowplow-snowflake-loader#11]
Part of #3

Before modifying any data we can check that all necessary entities such as stage, schema, table, file format exist.

**Comment by alexanderdean** [comment]
Add preliminary checks for what? Improve ticket/commit title

**Comment by chuwy** [comment]
Everything in ticket description already.

**Comment by alexanderdean** [comment]
Updated title
