### ISSUE TITLE
Separate AWS region from Snowflake region

### ISSUE THREAD

**Issue by chuwy** [snowplow-archive/snowplow-snowflake-loader#12]
Right now this is single `--aws-region` option, which means all AWS services (EMR, DynamoDB, S3) can be used only from [four regions](https://docs.snowflake.net/manuals/user-guide/intro-editions.html#label-snowflake-regions) that Snowflake supports. Otherwise invalid Snowflake endpoint will be used.

See https://github.com/snowplow-product/snowplow-snowflake-loader/issues/6

**Comment by alexanderdean** [comment]
Makes sense, but I think non-critical
