### ISSUE TITLE
Make Transformer 0.4.x compatible with 0.8.0 config

### ISSUE THREAD

**Issue by dilyand** [snowplow-archive/snowplow-snowflake-loader#129]
Transformer 0.7.0+ has known performance issues and therefore when we upgrade pipelines to the new Snowflake Loader, the Transformer has to be downgraded to 0.4.2 using a hacky workaround (separate config files). 

Until we fix the performance issues with the Transformer we need a way to be sure that the Transformer without the performance issues can be deployed along with Loader latest version, without fudging the configs.  

For this we need the transformer 0.4.3 to be compatible with the new storage integration configs.

**Comment by chuwy** [comment]
Renamed the ticket
