### ISSUE TITLE
Rename the userAgent JDBC connection property to application

### ISSUE THREAD

**Issue by dilyand** [snowplow-archive/snowplow-snowflake-loader#132]
We set a custom JDBC connection property called `userAgent`: 

```
// Build connection properties
      val properties = new Properties()
      (...)
      val userAgent = ProjectMetadata.name + "/" + ProjectMetadata.version
      (...)
      properties.put("userAgent", userAgent)
```

This is meant to be used to identify Snowplow as a Snowflake partner. However, according to the Snowflake documentation, this property must be called `application`: 

> `application=<string>`
Snowflake partner use only: Specifies the name of a partner application to connect through JDBC.

*Source:* https://docs.snowflake.com/en/user-guide/jdbc-configure.html#connection-parameters

**Comment by chuwy** [comment]
Ref ticket: https://github.com/snowplow-incubator/snowplow-snowflake-loader/issues/52
