### ISSUE TITLE
Fix jdbcHost derivation

### ISSUE THREAD

**Issue by oguzhanunlu** [snowplow-archive/snowplow-snowflake-loader#137]
https://github.com/snowplow-incubator/snowplow-snowflake-loader/blob/a593dd67853d5af278eb4b9adb0b39b8914888a3/loader/src/main/scala/com.snowplowanalytics.snowflake.loader/connection/Jdbc.scala#L40-L53

jdbcHost derivation considers AWS only which results in invalid connection strings for GCP & Azure. The logic should be extended to consider GCP and Azure regions as well.

See https://docs.snowflake.com/en/user-guide/intro-regions.html#supported-cloud-regions

**Comment by chuwy** [comment]
Seems to be a duplicate? https://github.com/snowplow-incubator/snowplow-snowflake-loader/issues/131

**Comment by oguzhanunlu** [comment]
right, I didn't notice that one, closing this in favor of the original one
