### ISSUE TITLE
Fix loading of NULLs as strings

### ISSUE THREAD

**Issue by dilyand** [snowplow-archive/snowplow-snowflake-loader#14]
It looks like `NULL` values are being loaded as `'null'` strings in Snowflake. That creates inconsistency, eg when performing outer joins -- we end up with a column where `NULL` s and `'null'`s get mixed.

**Comment by alexanderdean** [comment]
@chuwy has this been fixed in the 0.2.0? Speak to @dilyand about this please.

**Comment by chuwy** [comment]
@alexanderdean no, unfortunately it wasn't.

**Comment by chuwy** [comment]
It seems that we need to add `STRIP_NULL_VALUE` ([docs](https://docs.snowflake.net/manuals/sql-reference/functions/strip_null_value.html)) when loading data from temporary table to `atomic.events`. Some more references: [1][considerations], [2][parse-json]

[considerations]: https://docs.snowflake.net/manuals/user-guide/semistructured-considerations.html#parsing-null-values
[parse-json]: https://docs.snowflake.net/manuals/sql-reference/functions/parse_json.html

**Comment by alexanderdean** [comment]
Okay, let's keep this as an 0.3.0. We need to wrap the 0.2.0 release...
