### ISSUE TITLE
Use self-describing configuration

### ISSUE THREAD

**Issue by chuwy** [snowplow-archive/snowplow-snowflake-loader#19]
We will need to publish Iglu Central release with `iglu:com.snowplowanalytics.snowplow.storage/snowflake_config/jsonschema/1-0-0` along with 0.3.0

Part of transition #16

**Comment by alexanderdean** [comment]
Can you prepare the branch ASAP? (It's fine to do it in public.) I am working on an Iglu Central release this week so this can go in.

**Comment by chuwy** [comment]
Sure!
