### ISSUE TITLE
Add AWS credentials to stage or drop stages at all

### ISSUE THREAD

**Issue by chuwy** [snowplow-archive/snowplow-snowflake-loader#20]
Snowflake [external stages](https://docs.snowflake.net/manuals/sql-reference/sql/create-stage.html) are entities responsible for storing reference (URL) to some S3 location along with credentials (optionally) and some configuration. 

We started to create stages on `setup` in first 0.1.0 release candidates, because they were necessary for on-fly JSON transformations, but in final release we moved away from "on-fly transformations" to "temporary table" approach where stages are not necessary.

While stages are not useful for loading itself anymore, they can store AWS credentials for S3 access. With AWS creds stored inside stage it won't be necessary to launch `load` with **S3** creds (still required for DynamoDB access, but manifests table is not a sensitive data and separate AWS role can be used).

Option 1: make Snowflake responsible for storing credentials, don't pass them on each `load`
Option 2: if user provided stage - expect to find credentials there, if not use ones provided with `--awsAccessKey`
Option 3: don't use stages at all, pass creds on each `load`

First and second options also give user some power over [`config_options`](https://docs.snowflake.net/manuals/sql-reference/sql/copy-into-table.html) (size limit, parse error handing, etc), but I don't find it particularly useful in our case.

Third option make things easier: most of things configured only in our storage config, make stage URL and transformer output unlikely to be out of sync, etc

**Comment by alexanderdean** [comment]
I'm reading option 3 as operationally simpler and potentially more secure?

**Comment by chuwy** [comment]
Operationally simpler - for sure, secure - not sure. We're providing creds to Snowflake anyway, but with third option we don't need to store them on orchestration cluster and expose in EMR console if we're running loader as EMR step. So, it depends I think.

**Comment by alexanderdean** [comment]
Is there a typo in your last comment? It seems to contradict your previous point.

**Comment by chuwy** [comment]
Yes, sorry. With first and second option we don't expose creds in EMR and and don't store them on cluster.

**Comment by alexanderdean** [comment]
Got it, thanks. How securely does Snowflake store the S3 creds?

**Comment by chuwy** [comment]
Couldn't find anything regarding their security approach, but at least it is not possible to get/show/`describe` stored AWS Secret key.

**Comment by chuwy** [comment]
Pushed [config](https://github.com/snowplow/iglu-central/pull/635) based on Option 3.

**Comment by alexanderdean** [comment]
Do we need to switch to Option 2 given #32?
