### ISSUE TITLE
Use transaction for altering table and load

### ISSUE THREAD

**Issue by chuwy** [snowplow-archive/snowplow-snowflake-loader#25]
It'll make loading essentially atomic. 

I can predict only two possible manifest-inconsistency cases when this will be implemented:
1. **Transformer** fails, run id stuck in `processing` state and pipeline operator will have to delete it from manifest. We need add a check that scans table for  **processing** run ids. This can be used as lock, notifying that something went wrong with previous run. Right now it seems these folders will be "lost". 
2. Loader loaded data, but fails to mark it as loaded in manifest.
2.1 It can happen with relatively low probability.
2.2 This can also be discovered with check mentioned in `1` and easily fixed manually.

I think this simple mechanism solves https://github.com/snowplow-product/snowplow-snowflake-loader/issues/3 and makes loader and manifest extremely robust from my point of view.

See https://docs.snowflake.net/manuals/sql-reference/transactions.html

**Comment by alexanderdean** [comment]
Agree, this is important for the next release.
