### ISSUE TITLE
Allow loader to use the full AWS credentials chain

### ISSUE THREAD

**Issue by alexanderdean** [snowplow-archive/snowplow-snowflake-loader#32]
Currently the AWS creds must be passed on the command-line, which is not secure when the Loader is run as an EMR jobflow step.

**Comment by chuwy** [comment]
Loader uses credentials for two steps:

1. Discovering state through DynamoDB
2. Loading data to Snowflake

While for former we can use credentials chain, later one implies that Snowflake admin will have to add another credentials to Snowflake stage (as described in https://github.com/snowplow-incubator/snowplow-snowflake-loader/issues/20).

**Comment by alexanderdean** [comment]
Does that mean that we need to change our treatment of the Snowflake stage in #20?

**Comment by chuwy** [comment]
Yes, exactly, also it means Snowflake-setup will require admin to add credentials to stage. But I actually liked this approach much from the beginning.

**Comment by alexanderdean** [comment]
Cool!
