### ISSUE TITLE
Add cross-batch natural deduplication

### ISSUE THREAD

**Issue by chuwy** [snowplow-archive/snowplow-snowflake-loader#33]
See https://github.com/snowplow/snowplow/issues/2999

We have to extract it from shred.

**Comment by alexanderdean** [comment]
I think there's an interesting question about whether we keep the same DynamoDB-based architecture or switch to a Snowflake-based architecture.

Basically the Snowflake-based architecture would involve us loading the un-duped data into Snowflake, then performing the dedupe in place in Snowflake.

There are pros and cons. The pro is that we remove the DynamoDB-dependency, which also makes this loader less AWS-specific.

**Comment by chuwy** [comment]
Hey @alexanderdean, is architecture still an open question? I would prefer to go with exactly same approach as with RDB Shredder (but with [separate module](https://github.com/snowplow-incubator/snowplow-deduplication) extracted from RDB Shredder).

The core of that module is basically `save(event: Event): IO[Boolean]` function, which can be implemented atop of other storages (although conditional writes make it very performant on DynamoDB).

**Comment by alexanderdean** [comment]
Happy for us to go with the same architecture!
