### ISSUE TITLE
Truncate string values exceeding column's limits

### ISSUE THREAD

**Issue by chuwy** [snowplow-archive/snowplow-snowflake-loader#42]
RDB Loader truncates columns for both atomic and shredded types: https://github.com/snowplow/snowplow-rdb-loader/blob/master/src/main/scala/com/snowplowanalytics/snowplow/rdbloader/loaders/RedshiftLoadStatements.scala#L140

Snowflake loader instead fails after hitting longer column.

**Comment by userkci** [comment]
We've run into this issue and a workaround/alternative solution provided by Snowflake is to redefine the column type without the precision specified - VARCHAR versus VARCHAR(XXX).  This can even be applied to an already existing table, as Snowflake permits widening character types with ALTER TABLE .. ALTER COLUMN.

**Comment by chuwy** [comment]
https://github.com/snowplow/iglu-central/issues/778 should be used.
