### ISSUE TITLE
Add ON_ERROR setting

### ISSUE THREAD

**Issue by chuwy** [snowplow-archive/snowplow-snowflake-loader#43]
Equivalent to Redshift's `MAXERROR`, but skips work on file-base rather than load-base.

**Comment by chuwy** [comment]
> ON_ERROR = { CONTINUE | SKIP_FILE | SKIP_FILE_number | SKIP_FILE_number% | ABORT_STATEMENT }
>
>    String that specifies the action to perform when an error is encountered while loading data from a file:
>
>            CONTINUE: Continue loading the file.
>            SKIP_FILE: Skip file if any errors encountered in the file.
>            SKIP_FILE_number (e.g. SKIP_FILE_10): Skip file when the number of errors in the file exceeds the specified number.
>            SKIP_FILE_number% (e.g. SKIP_FILE_10%): Skip file when the percentage of errors in the file exceeds the specified percentage.
>            ABORT_STATEMENT: Abort the COPY statement if any error is encountered.
>
>    Default value is ABORT_STATEMENT.

**Comment by alexanderdean** [comment]
This feature will be super-helpful and critical for getting a blocked loader unblocked.

On the other hand, it's easy to use this as a "band-aid" instead of fixing an underlying problem - we need to make sure we always flag any underlying bugs in the loader whenever we are bumping this value!

**Comment by colmsnowplow** [comment]
Is it possible that skipped files go to a bucket in a similar fashion to the bad events bucket - so one could take a look at volume and causes of the loading issues and debug?

Eg. ~.01% - ~.5% of events don't load because of some corrupt value it might not be a massive short term problem for an analyst, but might be fixable in the tracking in the next iteration.

**Comment by chuwy** [comment]
Yeah, we don't have bad-bucket analog in Snowflake, but I like this idea of upfront validation.

**Comment by alexanderdean** [comment]
Nice idea @colmsnowplow !

**Comment by chuwy** [comment]
This should be a configuration option in snowflake configuration file. `maxError`
