### ISSUE TITLE
Load custom events and contexts as the same objects

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow-archive/snowplow-snowflake-loader#49]
From looking at the data, it appears that contexts end up in a column in `atomic.events` as a json object inside an array, whereas custom events end up as simply a json object.

I'm not sure of the technical limitations, but from the point of view of NCX and using the data, it would be best if they're of the same format.

As an example, this is the query to get the page view `id` from the web page context:

```
SELECT contexts_com_snowplowanalytics_snowplow_web_page_1[0]:id FROM atomic.events
```

And this is the query to get the `targetUrl` from a link click event:

```
SELECT unstruct_event_com_snowplowanalytics_snowplow_link_click_1:targetUrl FROM atomic.events
```

If it's possible to have these of the same format, I think we should do so.

**Comment by chuwy** [comment]
Hi @colmsnowplow, no sorry, I don't think it is possible. This is a very core concept of contexts that particular event can have multiple of them. And by "multiple" I mean even several contexts of exactly same schema. Although I know in most real-world cases we have only one context of particular schema. 

Still, sending two imaginary `com.acme/previous_state/jsonschema/1-0-0` contexts with single `com.acme/result/jsonschema/1-0-0` event is totally valid and there's no way to express this possibility without arrays.

**Comment by colmsnowplow** [comment]
That does make sense. No worries, thanks for the explanation!

**Comment by chuwy** [comment]
So, this is a core difference from my point of view.

* Self-describing event - always 1:1 relation (entity:event)
* Context - 1:zero-or-more relation (entity/event:contexts)

Though, I noticed that many modelings indeed imply exactly one context (or at least zero-or-one) - in that case you might want to raise issue to snowplow/snowplow, as it touches too many Snowplow design decisions.

**Comment by colmsnowplow** [comment]
Thanks. I think the argument to leave it the way it is currently is too strong - it doesn't make sense to tread different numbers of contexts differently.

**Comment by chuwy** [comment]
Ok, cool. Closing then.
