### ISSUE TITLE
Fix silent skip for folder outside of a stage

### ISSUE THREAD

**Issue by chuwy** [snowplow-archive/snowplow-snowflake-loader#62]
If we specify that data resides in `snowplow_stage`, but in fact data is outside it, warehouse simply skips folder and loader marks folder as loaded.

**Comment by alexanderdean** [comment]
What does it mean that data is "outside" it @chuwy?

**Comment by chuwy** [comment]
If stage is `s3://snowplow-data/snowflake-stage/`, but folders are in `s3://snowplow-data/other-folder/`, they can be considered outside of the stage.

This bug should not affect normally operating pipelines, but can cause "blank loads" for complex recovery/historical load scenarios.
