### ISSUE TITLE
Bump Snowflake JDBC driver to 3.11.0

### ISSUE THREAD

**Issue by chuwy** [snowplow-archive/snowplow-snowflake-loader#69]

**Comment by chuwy** [comment]
@rzats could you please incorporate this into current release.

**Comment by rzats** [comment]
Leaving this out of 0.4.0 due to an issue where the Snowflake JDBC driver logs AWS credentials in plaintext: https://github.com/snowflakedb/snowflake-jdbc/issues/70.
