### ISSUE TITLE
Change file format to JSON

### ISSUE THREAD

**Issue by alexanderdean** [snowplow-archive/snowplow-snowflake-loader#7]

**Comment by chuwy** [comment]
Renamed ticket to reflect actual change. 

Background: we were using `FILE_FORMAT = CSV` as advised in [docs](https://docs.snowflake.net/manuals/user-guide/data-load-transform.html), but apparently it fails to parse double backslash `//`, which is basically escaped slash. Changing format to `JSON` should fix this issue, though not clear if it is known difference between Snowflake CSV and JSON formats.
