### ISSUE TITLE
Make it possible to selectively skip setup steps

### ISSUE THREAD

**Issue by jbeemster** [snowplow-archive/snowplow-snowflake-loader#78]
In some accounts you might not want to grant the setup user SYSADMIN permissions or you might have a warehouse etc that already exists.  It would be good to be able to skip any of the steps for setup to alleviate this.

cc/ @chuwy

**Comment by chuwy** [comment]
I think this should be implemented with optional `--skip` flag, which can accept list of steps to skip e.g. `table,warehouse` would skip `events` table and warehouse creation.

https://github.com/snowplow-incubator/snowplow-snowflake-loader/blob/master/loader/src/main/scala/com.snowplowanalytics.snowflake.loader/Initializer.scala#L29-L34

Scheduling for 0.5.0.
